const ALL_EMAIL = {
  LOAD: 'ALL_EMAIL_LOAD',
  LOAD_SUCCESS: 'ALL_EMAIL_LOAD_SUCCESS',
  LOAD_FAIL: 'ALL_EMAIL_LOAD_FAIL'
};
const EMAIL = {
  LOAD: 'EMAIL_LOAD',
  LOAD_SUCCESS: 'EMAIL_LOAD_SUCCESS',
  LOAD_FAIL: 'EMAIL_LOAD_FAIL'
};

export { ALL_EMAIL,EMAIL };
