const NOTIFICATION = {
  LOAD: 'NOTIFICATION_LOAD',
  LOAD_SUCCESS: 'NOTIFICATION_LOAD_SUCCESS',
  LOAD_FAIL: 'NOTIFICATION_LOAD_FAIL'
};

const MESSAGE_COUNT = {
  LOAD: 'MESSAGE_COUNT_LOAD',
  LOAD_SUCCESS: 'MESSAGE_COUNT_LOAD_SUCCESS',
  LOAD_FAIL: 'MESSAGE_COUNT_LOAD_FAIL'
};

const MESSAGE_UNREAD = {
  LOAD: 'MESSAGE_UNREAD_LOAD',
  LOAD_SUCCESS: 'MESSAGE_UNREAD_LOAD_SUCCESS',
  LOAD_FAIL: 'MESSAGE_UNREAD_LOAD_FAIL'
};
const TOTAL_NOTIF = {
  LOAD: 'TOTAL_NOTIF_LOAD',
  LOAD_SUCCESS: 'TOTAL_NOTIF_LOAD_SUCCESS',
  LOAD_FAIL: 'TOTAL_NOTIF_LOAD_FAIL'
};
const PAGE = {
  LOAD: 'PAGE_LOAD',
  LOAD_SUCCESS: 'PAGE_LOAD_SUCCESS',
  LOAD_FAIL: 'PAGE_LOAD_FAIL'
};

export { NOTIFICATION, MESSAGE_COUNT, MESSAGE_UNREAD,TOTAL_NOTIF,PAGE };
