const DATA_CHART = {
  LOAD: 'DATA_CHART_LOAD',
  LOAD_SUCCESS: 'DATA_CHART_LOAD_SUCCESS',
  LOAD_FAIL: 'DATA_CHART_LOAD_FAIL'
};
const CHANGE_TITLE = {
  LOAD_SUCCESS: 'CHANGE_TITLE_LOAD_SUCCESS',
};
const CHANGE_CHART = {
  LOAD_SUCCESS: 'CHANGE_CHART_LOAD_SUCCESS',
};

export { DATA_CHART,CHANGE_TITLE,CHANGE_CHART };
