const TAGS = {
  LOAD: "TAGS_LOAD",
  LOAD_SUCCESS: "TAGS_LOAD_SUCCESS",
  LOAD_FAIL: "TAGS_LOAD_FAIL",
};

const CAMERA_TAGS = {
  LOAD: "CAMERA_TAGS_LOAD",
  LOAD_SUCCESS: "CAMERA_TAGS_LOAD_SUCCESS",
  LOAD_FAIL: "CAMERA_TAGS_LOAD_FAIL",
};

export { TAGS, CAMERA_TAGS };
