const OPENMODALPRESETSETTING = {
  LOAD_SUCCESS: "OPEN_MODAL_PRESET_SETTING_LOAD_SUCCESS",
};
const UPDATE_DATA = {
  LOAD_SUCCESS: "UPDATE_DATA_SUCCESS",
};

export { OPENMODALPRESETSETTING, UPDATE_DATA };
