
export const MAP_SET_STYLE = 'MAP_SET_STYLE';
export const RESET_MAP_OBJECT = 'RESET_MAP_OBJECT'
export const UPDATE_MAP_OBJECT = 'UPDATE_MAP_OBJECT';
export const UPDATE_STYLE_MAP = 'UPDATE_STYLE_MAP'

// declare action type for camera on map
export const FETCH_ALL_CAMERA_ON_MAP = 'FETCH_ALL_CAMERA_ON_MAP';
export const FETCH_ALL_CAMERA_ON_MAP_SUCCESS = 'FETCH_ALL_CAMERA_ON_MAP_SUCCESS';
export const FETCH_ALL_CAMERA_ON_MAP_FAILED = 'FETCH_ALL_CAMERA_ON_MAP_FAILED';

export const ADD_CAMERA_ON_MAP = 'ADD_CAMERA_ON_MAP';
export const ADD_CAMERA_ON_MAP_SUCCESS = 'ADD_CAMERA_ON_MAP_SUCCESS';
export const ADD_CAMERA_ON_MAP_FAILED = 'ADD_CAMERA_ON_MAP_FAILED';

export const UPDATE_CAMERA_ON_MAP = 'UPDATE_CAMERA_ON_MAP';
export const UPDATE_CAMERA_ON_MAP_SUCCESS = 'UPDATE_CAMERA_ON_MAP_SUCCESS';
export const UPDATE_CAMERA_ON_MAP_FAILED = 'UPDATE_CAMERA_ON_MAP_FAILED';

export const UPDATE_CAMERA_ON_MAP_BY_TRACKING_POINT = 'UPDATE_CAMERA_ON_MAP_BY_TRACKING_POINT'
export const UPDATE_CAMERA_ON_MAP_BY_TRACKING_POINT_SUCCESS = 'UPDATE_CAMERA_ON_MAP_BY_TRACKING_POINT_SUCCESS'
export const UPDATE_CAMERA_ON_MAP_BY_TRACKING_POINT_FAILED = 'UPDATE_CAMERA_ON_MAP_BY_TRACKING_POINT_FAILED'

export const UPDATE_CAMERA_ON_MAP_BY_FILTER = 'UPDATE_CAMERA_ON_MAP_BY_FILTER'
export const UPDATE_CAMERA_ON_MAP_BY_FILTER_SUCCESS = 'UPDATE_CAMERA_ON_MAP_BY_FILTER_SUCCESS'
export const UPDATE_CAMERA_ON_MAP_BY_FILTER_FAILED = 'UPDATE_CAMERA_ON_MAP_BY_FILTER_FAILED'

export const CAMERA_APP_FILTER = 'CAMERA_APP_FILTER'

// declare action type for adminis units on map
export const FETCH_ALL_ADMINIS_UNITS_ON_MAP = 'FETCH_ALL_ADMINIS_UNITS_ON_MAP ';
export const FETCH_ALL_ADMINIS_UNITS_ON_MAP_SUCCESS = 'FETCH_ALL_ADMINIS_UNITS_ON_MAP_SUCCESS';
export const FETCH_ALL_ADMINIS_UNITS_ON_MAP_FAILED = 'FETCH_ALL_ADMINIS_UNITS_ON_MAP_FAILED';

export const ADD_ADMINIS_UNIT_ON_MAP = 'ADD_ADMINIS_UNIT_ON_MAP ';
export const ADD_ADMINIS_UNIT_ON_MAP_SUCCESS = 'ADD_ADMINIS_UNIT_ON_MAP_SUCCESS';
export const ADD_ADMINIS_UNIT_ON_MAP_FAILED = 'ADD_ADMINIS_UNIT_ON_MAP_FAILED';

export const UPDATE_ADMINIS_UNIT_ON_MAP = 'UPDATE_ADMINIS_UNIT_ON_MAP';
export const UPDATE_ADMINIS_UNIT_ON_MAP_SUCCESS = 'UPDATE_ADMINIS_UNIT_ON_MAP_SUCCESS';
export const UPDATE_ADMINIS_UNIT_ON_MAP_FAILED = 'UPDATE_ADMINIS_UNIT_ON_MAP_FAILED';

export const UPDATE_ADMINIS_UNIT_ON_MAP_BY_TRACKING_POINT = 'UPDATE_ADMINIS_UNIT_ON_MAP_BY_TRACKING_POINT'
export const UPDATE_ADMINIS_UNIT_ON_MAP_BY_TRACKING_POINT_SUCCESS = 'UPDATE_ADMINIS_UNIT_ON_MAP_BY_TRACKING_POINT_SUCCESS'
export const UPDATE_ADMINIS_UNIT_ON_MAP_BY_TRACKING_POINT_FAILED = 'UPDATE_ADMINIS_UNIT_ON_MAP_BY_TRACKING_POINT_FAILED'

export const UPDATE_ADMINIS_UNIT_ON_MAP_BY_FILTER = 'UPDATE_ADMINIS_UNIT_ON_MAP_BY_FILTER'
export const UPDATE_ADMINIS_UNIT_ON_MAP_BY_FILTER_SUCCESS = 'UPDATE_ADMINIS_UNIT_ON_MAP_BY_FILTER_SUCCESS'
export const UPDATE_ADMINIS_UNIT_ON_MAP_BY_FILTER_FAILED = 'UPDATE_ADMINIS_UNIT_ON_MAP_BY_FILTER_FAILED'

export const EDIT_ADMINIS_UNIT_INFO = 'EDIT_ADMINIS_UNIT_INFO';
export const ADD_ADMINIS_UNIT_INFO = 'ADD_ADMINIS_UNIT_INFO';

// declare action type for tracking point on map
export const FETCH_ALL_TRACKING_POINT_ON_MAP = 'FETCH_ALL_TRACKING_POINT_ON_MAP ';
export const FETCH_ALL_TRACKING_POINT_ON_MAP_SUCCESS = 'FETCH_ALL_TRACKING_POINT_ON_MAP_SUCCESS';
export const FETCH_ALL_TRACKING_POINT_ON_MAP_FAILED = 'FETCH_ALL_TRACKING_POINT_ON_MAP_FAILED';

export const DELETE_ONE_TRACKING_POINT_ON_MAP = 'DELETE_ONE_TRACKING_POINT_ON_MAP ';
export const DELETE_ONE_TRACKING_POINT_ON_MAP_SUCCESS = 'DELETE_ONE_TRACKING_POINT_ON_MAP_SUCCESS';
export const DELETE_ONE_TRACKING_POINT_ON_MAP_FAILED = 'DELETE_ONE_TRACKING_POINT_ON_MAP_FAILED';

export const DELETE_ALL_TRACKING_POINT_ON_MAP = 'DELETE_ALL_TRACKING_POINT_ON_MAP ';
export const DELETE_ALL_TRACKING_POINT_ON_MAP_SUCCESS = 'DELETE_ALL_TRACKING_POINT_ON_MAP_SUCCESS';
export const DELETE_ALL_TRACKING_POINT_ON_MAP_FAILED = 'DELETE_ALL_TRACKING_POINT_ON_MAP_FAILED';

export const ADD_TRACKING_POINT_ON_MAP = 'ADD_TRACKING_POINT_ON_MAP ';
export const ADD_TRACKING_POINT_ON_MAP_SUCCESS = 'ADD_TRACKING_POINT_ON_MAP_SUCCESS';
export const ADD_TRACKING_POINT_ON_MAP_FAILED = 'ADD_TRACKING_POINT_ON_MAP_FAILED';
export const ADD_TRACKING_POINT = 'ADD_TRACKING_POINT';
export const UPDATE_TRACKING_POINT = 'UPDATE_TRACKING_POINT';
export const DELETE_TRACKING_POINT = 'DELETE_TRACKING_POINT';
export const UPDATE_CURRENT_LANG = 'UPDATE_CURRENT_LANG';
export const SET_SELECTED_TRACKING_POINT = 'SET_SELECTED_TRACKING_POINT'
export const REMOVE_TRACKING_POINT = 'REMOVE_TRACKING_POINT';
export const SET_TRACKING_POINTS_ON_MAP = 'SET_TRACKING_POINTS_ON_MAP';
export const SET_CAMS_LIVE = 'SET_CAMS_LIVE';
export const REMOVE_CAM_LIVE = 'REMOVE_CAM_LIVE';
export const UPDATE_CAM_LIVE = 'UPDATE_CAM_LIVE';
export const NOT_PERMISSION_VIEW_CAM = 'NOT_PERMISSION_VIEW_CAM';
export const NOT_OPERATION_VIEW_CAM = 'NOT_OPERATION_VIEW_CAM';
export const REMOVE_ALL_CAM_LIVE = 'REMOVE_ALL_CAM_LIVE';
export const SELECT_OR_DESELECT_CAMERA_LIVE = 'SELECT_OR_DESELECT_CAMERA_LIVE';
export const DESELECT_CAMERA_LIVE = 'DESELECT_CAMERA_LIVE'
export const SET_PLAYBACK_HLS = 'SET_PLAYBACK_HLS'
export const PLAYBACK_SEEK_TIME = 'PLAYBACK_SEEK_TIME';
export const UPDATE_PLAYBACK_CAM = 'UPDATE_PLAYBACK_CAM';

export const GET_LIST_CAM_LIVE = 'GET_LIST_CAM_LIVE';
export const GET_LIST_CAM_LIVE_SUCCESS = 'GET_LIST_CAM_LIVE_SUCCESS';
export const GET_LIST_CAM_LIVE_ERROR = 'GET_LIST_CAM_LIVE_ERROR';
export const SAVE_LIST_CAM_LIVE = 'SAVE_LIST_CAM_LIVE';
export const SAVE_LIST_CAM_LIVE_SUCCESS = 'SAVE_LIST_CAM_LIVE_SUCCESS';
export const SAVE_LIST_CAM_LIVE_ERROR = 'SAVE_LIST_CAM_LIVE_ERROR';
export const UPDATE_LIST_CAM_LIVE = 'UPDATE_LIST_CAM_LIVE';
export const UPDATE_LIST_CAM_LIVE_SUCCESS = 'UPDATE_LIST_CAM_LIVE_SUCCESS';
export const UPDATE_LIST_CAM_LIVE_ERROR = 'UPDATE_LIST_CAM_LIVE_ERROR';

export const DELETE_LIST_CAM_LIVE = 'DELETE_LIST_CAM_LIVE';
export const DELETE_LIST_CAM_LIVE_SUCCESS = 'DELETE_LIST_CAM_LIVE_SUCCESS';
export const DELETE_LIST_CAM_LIVE_ERROR = 'DELETE_LIST_CAM_LIVE_ERROR';
